language: elixir
elixir:
  - 1.4.5
  - 1.5.3
  - 1.6.6
  - 1.7.4
  - 1.8.0
otp_release:
  - 19.0
  - 19.1
  - 20.0
  - 20.3.5
  - 21.0.5
  - 21.1.4
  - 21.2
matrix:
  exclude:
  - elixir: 1.4.5
    otp_release: 21.0.5
  - elixir: 1.4.5
    otp_release: 21.1.4
  - elixir: 1.4.5
    otp_release: 21.2
  - elixir: 1.5.3
    otp_release: 21.0.5
  - elixir: 1.5.3
    otp_release: 21.1.4
  - elixir: 1.5.3
    otp_release: 21.2
  - elixir: 1.8.0
    otp_release: 19.0
  - elixir: 1.8.0
    otp_release: 19.1

sudo: false
